Algorithm for zeroing the elements that are equal to the element in p…
YESENIA2012/Logicadeprogramacion pull request #3
Opened 2021-09-28 17:15 UTC by YESENIA2012

This is the algorithm, you can check it boss ?

2021-09-28 17:36 UTC, YESENIA2012 commented
Can you review it please

2021-09-28 18:17 UTC, erick2014 requested changes

2021-09-28 18:17 UTC, erick2014 commented on changeVectorElementZero.js
> +console.log(primerElemento);
please remove this console.log

2021-09-28 18:21 UTC, YESENIA2012 commented on changeVectorElementZero.js
> +console.log(primerElemento);
console.log has already been removed

2021-10-05 19:00 UTC, erick2014 commented
well done!

2021-10-05 19:00 UTC, merged