Algorithm that adds the main and minor diagonal of a matrix
YESENIA2012/Logicadeprogramacion pull request #5
Opened 2021-10-07 17:27 UTC by YESENIA2012

You can review it my love ?

2021-10-13 23:16 UTC, YESENIA2012 commented
You can check it thingy, please.

2021-10-13 23:36 UTC, erick2014 commented on sumMainSecundaryDiagonal.js
> +*/
remove commented code from line 1 to line 21

2021-10-13 23:43 UTC, erick2014 requested changes

2021-10-13 23:43 UTC, erick2014 commented on sumMainSecundaryDiagonal.js
> +  var sumaDiagonalPrincipal = 0;
this should be declared with let, because declaring it with var will declare the variable globally:
let sumaDiagonalPrincipal = 0;

2021-10-13 23:43 UTC, erick2014 commented on sumMainSecundaryDiagonal.js
> +  var sumaDiagonalSecundaria = 0;
this should be declared with let, because declaring it with var will declare the variable globally:
let sumaDiagonalPrincipal = 0;

2021-10-13 23:43 UTC, erick2014 commented on sumMainSecundaryDiagonal.js
> +//console.log("Secundaria", diagonales.variableDeSumatoriaDiagonalSecundaria);
remove commented code from lines 43 to 47

2021-10-13 23:43 UTC, erick2014 commented on test/sumMainSecundaryDiagonal.test.js
> +describe("Sum of main and secundary Diagonals", function () {
change the message to something like: "Add sumatory of primary and secondary diagonals"

2021-10-13 23:43 UTC, erick2014 commented on test/sumMainSecundaryDiagonal.test.js
> +  it("should show the sum between the main and secondary diagonal", function () {
"should show the sum of primary and secondary diagonals equal 10 "

2021-10-13 23:43 UTC, erick2014 commented on test/sumMainSecundaryDiagonal.test.js
> +  it("it should show 0 as a result", function () {
add a break line on line 23 to separate the code

2021-10-14 01:28 UTC, YESENIA2012 commented
Again I made the changes because it was wrong, the previous

2021-10-15 02:11 UTC, merged